name: Flutter CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Flutter action
        uses: subosito/flutter-action@v2.2.1
        with:
          flutter-version: "2.5.3"
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "2.14.4"
      - name: Flutter pub get dependencies
        run: flutter pub get
      - name: Analyze project
        run: flutter analyze
