name: Flutter CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "15"
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.8.0"
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: '2.15.1'
      - name: Flutter pub get dependencies
        run: flutter pub get
      - name: Analyze project
        run: flutter analyze